# NumPy

Numpy introduction
------------------

The NumPy package (read as NUMerical PYthon) provides access to

-   a new data structure called `array`s which allow

-   efficient vector and matrix operations. It also provides

-   a number of linear algebra operations (such as solving of systems of linear equations, computation of Eigenvectors and Eigenvalues).

### History

Some background information: There are two other implementations that provide nearly the same functionality as NumPy. These are called “Numeric” and “numarray”:

-   Numeric was the first provision of a set of numerical methods (similar to Matlab) for Python. It evolved from a PhD project.

-   Numarray is a re-implementation of Numeric with certain improvements (but for our purposes both Numeric and Numarray behave virtually identical).

-   Early in 2006 it was decided to merge the best aspects of Numeric and Numarray into the Scientific Python (<span>`scipy`</span>) package and to provide (a hopefully “final”) `array` data type under the module name “NumPy”.

We will use in the following materials the “NumPy” package as provided by (new) SciPy. If for some reason this doesn’t work for you, chances are that your SciPy is too old. In that case, you will find that either “Numeric” or “numarray” is installed and should provide nearly the same capabilities.[5]

### Arrays

We introduce a new data type (provided by NumPy) which is called “`array`”. An array *appears* to be very similar to a list but an array can keep only elements of the same type (whereas a list can mix different kinds of objects). This means arrays are more efficient to store (because we don’t need to store the type for every element). It also makes arrays the data structure of choice for numerical calculations where we often deal with vectors and matricies.

Vectors and matrices (and matrices with more than two indices) are all called “arrays” in NumPy.

#### Vectors (1d-arrays)

The data structure we will need most often is a vector. Here are a few examples of how we can generate one:

# Array Creation and Properties

There are a lot of ways to create arrays.  Let's look at a few

Here we create an array using `arange` and then change its shape to be 3 rows and 5 columns.

In [14]:
import numpy as np

In [15]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
b=range(20)
print(b)

range(0, 20)


In [19]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


A NumPy array has a lot of meta-data associated with it describing its shape, datatype, etc.

In [20]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [21]:
c=np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


`linspace` (and `logspace`) create arrays with evenly space (in log) numbers.  For `logspace`, you specify the start and ending powers (`base**start` to `base**stop`)

In [25]:
d=np.linspace(0,2,20,endpoint=False)
print(d)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [28]:
e=np.logspace(0,2,20,endpoint=False,base=10)
print(e)

[ 1.          1.25892541  1.58489319  1.99526231  2.51188643  3.16227766
  3.98107171  5.01187234  6.30957344  7.94328235 10.         12.58925412
 15.84893192 19.95262315 25.11886432 31.6227766  39.81071706 50.11872336
 63.09573445 79.43282347]


As always, as for help -- the numpy functions have very nice docstrings

In [29]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

we can also initialize an array based on a function

In [39]:
f=np.fromfunction(lambda i,j:i==j,(3,5),dtype=int)
print(f)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]]


# Array Operations

most operations (`+`, `-`, `*`, `/`) will work on an entire array at once, element-by-element.

Note that that the multiplication operator is not a matrix multiply (there is a new operator in python 3.5+, `@`, to do matrix multiplicaiton.

Let's create a simply array to start with

In [57]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Multiplication by a scalar multiplies every element

In [58]:
a*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

adding two arrays adds element-by-element

In [59]:
a+a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

multiplying two arrays multiplies element-by-element

In [60]:
a*a

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

We can think of our 2-d array a was a 3 x 5 matrix (3 rows, 5 columns).  We can take the transpose to geta 5 x 3 matrix, and then we can do a matrix multiplication

In [61]:
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
d.transpose()

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

We can sum along axes or the entire array

In [62]:
a.sum(axis=1)

array([10, 35])

In [63]:
a.sum()

45

Also get the extrema

In [64]:
print(a.min(),a.max())

0 9


### universal functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; now, we will dive into the reasons that NumPy is so important in the Python data science world.
Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

universal functions work element-by-element.  Let's create a new array scaled by `pi`

In [68]:
b=a*np.pi/12.0
print(b)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755]
 [1.30899694 1.57079633 1.83259571 2.0943951  2.35619449]]


In [71]:
c=np.sin(b)
print(c)

[[0.         0.25881905 0.5        0.70710678 0.8660254 ]
 [0.96592583 1.         0.96592583 0.8660254  0.70710678]]


In [72]:
d=b+c
print(d)

[[0.         0.52061843 1.02359878 1.49250494 1.91322295]
 [2.27492277 2.57079633 2.79852154 2.96042051 3.06330127]]


In [73]:
s=np.tan(d)
print(s)

[[ 0.          0.57338329  1.64134635 12.74669007 -2.80528909]
 [-1.17734742 -0.64209262 -0.35719605 -0.18318075 -0.07845174]]


## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [74]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [77]:
even=np.arange(0,100,3)
print(even)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


Now look at accessing a single element vs. a range (using slicing)

Giving a single (0-based) index just references a single value

In [78]:
print(a[2:3])

[2]


In [79]:
a[2:4]

array([2, 3])

In [80]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Multidimensional Arrays

Multidimensional arrays are stored in a contiguous space in memory -- this means that the columns / rows need to be unraveled (flattened) so that it can be thought of as a single one-dimensional array.  Different programming languages do this via different conventions:


Storage order:

* Python/C use *row-major* storage: rows are stored one after the other
* Fortran/matlab use *column-major* storage: columns are stored one after another

The ordering matters when 

* passing arrays between languages (we'll talk about this later this semester)
* looping over arrays -- you want to access elements that are next to one-another in memory
  * e.g, in Fortran:
  <pre>
  double precision :: A(M,N)
  do j = 1, N
     do i = 1, M
        A(i,j) = …
     enddo
  enddo
  </pre>
  
  * in C
  <pre>
  double A[M][N];
  for (i = 0; i < M; i++) {
     for (j = 0; j < N; j++) {
        A[i][j] = …
     }
  }  
  </pre>
  

In python, using NumPy, we'll try to avoid explicit loops over elements as much as possible

Let's look at multidimensional arrays:

In [84]:
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Notice that the output of `a` shows the row-major storage.  The rows are grouped together in the inner `[...]`

Giving a single index (0-based) for each dimension just references a single value in the array

In [85]:
a[1,3]

8

Doing slices will access a range of elements.  Think of the start and stop in the slice as referencing the left-edge of the slots in the array.

In [86]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

Access a specific column

In [87]:
a[:1]

array([[0, 1, 2, 3, 4]])

Sometimes we want a one-dimensional view into the array -- here we see the memory layout (row-major) more explicitly

In [88]:
a=a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


we can also iterate -- this is done over the first axis (rows)

In [89]:
for r in a:
    print(r)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


or element by element

In [93]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [105]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

# Boolean Indexing

There are lots of fun ways to index arrays to access only those elements that meet a certain condition

In [108]:
a=np.arange(12).reshape(3,4)


In [107]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Here we set all the elements in the array that are > 4 to zero

In [112]:
a[a>4]=0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

and now, all the zeros to -1

In [114]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [115]:
a==-1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

if we have 2 tests, we need to use `logical_and()` or `logical_or()`

In [120]:
a=np.arange(12).reshape(3,4)
a[np.logical_and(a>3,a<=9)]=1
a

array([[ 0,  1,  2,  3],
       [ 1,  1,  1,  1],
       [ 1,  1, 10, 11]])

Our test that we index the array with returns a boolean array of the same shape:

In [121]:
a>4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

# Avoiding Loops

Python's default implementation (known as CPython) does some operations very slowly.
This is in part due to the dynamic, interpreted nature of the language: the fact that types are flexible, so that sequences of operations cannot be compiled down to efficient machine code as in languages like C and Fortran.
Recently there have been various attempts to address this weakness: well-known examples are the [PyPy](http://pypy.org/) project, a just-in-time compiled implementation of Python; the [Cython](http://cython.org) project, which converts Python code to compilable C code; and the [Numba](http://numba.pydata.org/) project, which converts snippets of Python code to fast LLVM bytecode.
Each of these has its strengths and weaknesses, but it is safe to say that none of the three approaches has yet surpassed the reach and popularity of the standard CPython engine.

The relative sluggishness of Python generally manifests itself in situations where many small operations are being repeated – for instance looping over arrays to operate on each element.

In general, you want to avoid loops over elements on an array.

Here, let's create 1-d x and y coordinates and then try to fill some larger array

In [128]:
M=32
N=64
x=np.linspace(0.0,1.0,M,endpoint=True)
y=np.linspace(0.0,1.0,N,endpoint=False)
print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

we'll time out code

In [136]:
import time
M=32
N=64
x=np.linspace(0.0,1.0,M,endpoint=True)
y=np.linspace(0.0,1.0,N,endpoint=False)
t0=time.time()
print(t0)
g=np.zeros((M,N))
print(g)
for i in range(M):
    for j in range(N):
        g[i,j]=np.sin(2.0*np.pi*x[i]*y[j])
t1=time.time()
print('time elapsed:{}s'.format(t1-t0))

1663577560.9709365
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
time elapsed:0.021937847137451172s


In [141]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])

[0.         0.03225806 0.06451613 0.09677419 0.12903226 0.16129032
 0.19354839 0.22580645 0.25806452 0.29032258 0.32258065 0.35483871
 0.38709677 0.41935484 0.4516129  0.48387097 0.51612903 0.5483871
 0.58064516 0.61290323 0.64516129 0.67741935 0.70967742 0.74193548
 0.77419355 0.80645161 0.83870968 0.87096774 0.90322581 0.93548387
 0.96774194 1.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 

Now let's instead do this using all array syntax.  First will extend our 1-d coordinate arrays to be 2-d

In [148]:
t0=time.time()
g2=np.sin(2*np.pi*x2d*y2d)
t1=time.time()
print(t1)
print(t0)

1663577993.2237563
1663577993.2081332


In [149]:
print("Time elasped:{}s".format(t1-t0))

Time elasped:0.015623092651367188s


## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types, which will be covered in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).

### Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object.
For example, if we'd like to *reduce* an array with a particular operation, we can use the ``reduce`` method of any ufunc.
A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling ``reduce`` on the ``add`` ufunc returns the sum of all elements in the array:

In [150]:
x=np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

Similarly, calling ``reduce`` on the ``multiply`` ufunc results in the product of all array elements:

In [151]:
np.add.reduce(x)

36

If we'd like to store all the intermediate results of the computation, we can instead use ``accumulate``:

In [152]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [153]:
np.multiply.reduce(x)

40320

In [154]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320],
      dtype=int32)